# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userroles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModeratorProfile',
            fields=[
                ('userrole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='userroles.UserRole')),
                ('stars', models.IntegerField()),
            ],
            bases=('userroles.userrole',),
        ),
    ]
